export type MemoryDataCategory =
  | "IDENTITY_AND_SECURITY"
  | "PRIMARY_MEMORY"
  | "DERIVED_PERSISTENT_MEMORY"
  | "LOCAL_WORK_STATE"
  | "SYNC_INFRASTRUCTURE"
  | "APPLICATION_INFRASTRUCTURE";

export type MemoryInventoryItem = {
  data: string;
  location: "PostgreSQL" | "IndexedDB" | "Browser storage" | "Runtime";
  category: MemoryDataCategory;
  isMemory: boolean;
  export: boolean;
  reset: boolean;
  restore: boolean;
  notes: string;
};

export const MEMORY_INVENTORY: MemoryInventoryItem[] = [
  {
    data: "User",
    location: "PostgreSQL",
    category: "IDENTITY_AND_SECURITY",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Cuenta, email y password hash. Se conserva.",
  },
  {
    data: "Workspace",
    location: "PostgreSQL",
    category: "APPLICATION_INFRASTRUCTURE",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Limite tecnico unico de la memoria activa. No visible al usuario.",
  },
  {
    data: "WorkspaceMember",
    location: "PostgreSQL",
    category: "IDENTITY_AND_SECURITY",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Vinculo usuario-memoria tecnica. Se conserva.",
  },
  {
    data: "Device",
    location: "PostgreSQL",
    category: "IDENTITY_AND_SECURITY",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Dispositivo confiable. Se conserva.",
  },
  {
    data: "AuthSession",
    location: "PostgreSQL",
    category: "IDENTITY_AND_SECURITY",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Sesion y refresh token hash. Se conserva y nunca se exporta.",
  },
  {
    data: "Capture",
    location: "PostgreSQL",
    category: "PRIMARY_MEMORY",
    isMemory: true,
    export: true,
    reset: true,
    restore: true,
    notes: "Capturas activas y archivadas.",
  },
  {
    data: "Concept",
    location: "PostgreSQL",
    category: "PRIMARY_MEMORY",
    isMemory: true,
    export: true,
    reset: true,
    restore: true,
    notes: "Conceptos aceptados activos y archivados.",
  },
  {
    data: "CaptureConcept",
    location: "PostgreSQL",
    category: "PRIMARY_MEMORY",
    isMemory: true,
    export: true,
    reset: true,
    restore: true,
    notes: "Relaciones captura-concepto.",
  },
  {
    data: "SyncChange",
    location: "PostgreSQL",
    category: "SYNC_INFRASTRUCTURE",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Registro tecnico de sync; conserva marcador de reset.",
  },
  {
    data: "ProcessedMutation",
    location: "PostgreSQL",
    category: "SYNC_INFRASTRUCTURE",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Idempotencia de sync; no es memoria del usuario.",
  },
  {
    data: "nodes",
    location: "IndexedDB",
    category: "PRIMARY_MEMORY",
    isMemory: true,
    export: true,
    reset: true,
    restore: true,
    notes: "Capturas locales activas y archivadas.",
  },
  {
    data: "contexts",
    location: "IndexedDB",
    category: "PRIMARY_MEMORY",
    isMemory: true,
    export: true,
    reset: true,
    restore: true,
    notes: "Conceptos locales aceptados.",
  },
  {
    data: "node_context_relations",
    location: "IndexedDB",
    category: "PRIMARY_MEMORY",
    isMemory: true,
    export: true,
    reset: true,
    restore: true,
    notes: "Relaciones locales.",
  },
  {
    data: "app_settings",
    location: "IndexedDB",
    category: "APPLICATION_INFRASTRUCTURE",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Preferencias y borrador mediante clave dedicada.",
  },
  {
    data: "vinema:capture-draft:v1",
    location: "Browser storage",
    category: "LOCAL_WORK_STATE",
    isMemory: false,
    export: false,
    reset: true,
    restore: false,
    notes: "Borrador local de captura; se limpia al reset.",
  },
  {
    data: "key-value",
    location: "IndexedDB",
    category: "APPLICATION_INFRASTRUCTURE",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Store heredado; el borrador se elimina tambien desde esta ubicacion.",
  },
  {
    data: "auth_session",
    location: "IndexedDB",
    category: "IDENTITY_AND_SECURITY",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Sesion local segura. Se conserva.",
  },
  {
    data: "devices",
    location: "IndexedDB",
    category: "IDENTITY_AND_SECURITY",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Dispositivo local. Se conserva.",
  },
  {
    data: "workspaces",
    location: "IndexedDB",
    category: "APPLICATION_INFRASTRUCTURE",
    isMemory: false,
    export: false,
    reset: false,
    restore: false,
    notes: "Workspace tecnico local. Se conserva.",
  },
  {
    data: "sync_mutations",
    location: "IndexedDB",
    category: "SYNC_INFRASTRUCTURE",
    isMemory: false,
    export: false,
    reset: true,
    restore: false,
    notes: "Outbox local; se limpia para evitar revivir memoria antigua.",
  },
  {
    data: "sync_metadata",
    location: "IndexedDB",
    category: "SYNC_INFRASTRUCTURE",
    isMemory: false,
    export: false,
    reset: true,
    restore: false,
    notes: "Cursores y errores; el cursor avanza al resetVersion.",
  },
  {
    data: "sync_entity_acknowledgements",
    location: "IndexedDB",
    category: "SYNC_INFRASTRUCTURE",
    isMemory: false,
    export: false,
    reset: true,
    restore: false,
    notes: "Ledger local de versiones reconocidas; se limpia en reset para no mezclar generaciones.",
  },
  {
    data: "association suggestions",
    location: "Runtime",
    category: "DERIVED_PERSISTENT_MEMORY",
    isMemory: false,
    export: false,
    reset: true,
    restore: false,
    notes: "Derivado en memoria desde nodes/contexts/relations; no persistido.",
  },
  {
    data: "emergent identity",
    location: "Runtime",
    category: "DERIVED_PERSISTENT_MEMORY",
    isMemory: false,
    export: false,
    reset: true,
    restore: false,
    notes: "Derivada desde contenido y relaciones; no se exporta como titulo.",
  },
];

export function getMemoryInventory() {
  return MEMORY_INVENTORY;
}
